
export const CHANGE_NAME='CHANGE_NAME';
export const CHANGE_SURNAME='CHANGE_SURNAME'
export const CHANGE_TYPEAB='CHANGE_TYPEAB'
export const CHANGE_EMAIL='EMAIL'
export const CHANGE_TEL='CHANGE_TEL'
export const CHANGE_DATE='CHANGE_DATE'
export const CHANGE_LOCATION='CHANGE_LOCATION'
export const CHANGE_ETAB='CHANGE_ETAB'
export const CHANGE_IDENTIF='CHANGE_IDENTIF'
export const CHANGE_ATTESTATION='CHANGE_ATTESTATION'
export const CHANGE_PHOTO='CHANGE_PHOTO'
export const CHANGE_METHOD='CHANGE_METHOD'
export const CHANGE_REF='CHANGE_REF'
export const CHANGE_ID='CHANGE_ID'

